version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped

  memgraph:
    image: memgraph/memgraph
    ports:
      - "7687:7687"
      - "3000:3000"
    environment:
      MEMGRAPH_BOLT_AUTH_ENABLED: "true"
      MEMGRAPH_BOLT_AUTH_USERNAME: "memgraph"
      MEMGRAPH_BOLT_AUTH_PASSWORD: "yourStrongPassword"  # Change this!
    restart: unless-stopped
